hashicorp/vault-plugin-secrets-ad

plugin/backend_test.go, plugin/passwordconf.go, plugin/path_config.go, plugin/path_creds.go, plugin/util/passwords.go, plugin/util/passwords_test.go
Armon asked:
>Can we allow a Sprintf style format string to be provided that we populate with random characters? That seems more flexible, and lets users work around a custom filter.
This PR adds that feature. TODO update corresponding docs in Vault.
=> Add ability to provide custom password format

plugin/backend.go, plugin/backend_test.go, plugin/path_rotate_root_creds.go, plugin/util/secrets_client.go
Adds an MVP endpoint to rotate root credentials. 
There are two caveats to this that need to be documented:
- The `bind_dn` parameter must be specific enough that searching for it hits exactly one account
- There can be a delay for this to propagate the new password that the code has not yet mitigated, so if it were rotated during high-load times, it could result in a period of a second or more where all password rotations failed
=> Add an endpoint to rotate root credentials

Makefile, plugin/backend.go, plugin/path_rotate_root_creds.go, plugin/path_rotate_root_creds_test.go
If a new root password can't be stored, attempts to roll back the remote AD servers to the old password.
=> Roll back if password unstored

plugin/backend.go, plugin/backend_test.go, plugin/client/client.go, plugin/client/client_test.go, plugin/client/config.go, plugin/client/tools/simplecall.go, plugin/engineconf.go, plugin/engineconf_test.go, plugin/path_config.go, plugin/path_rotate_root_creds_test.go, plugin/util/secrets_client.go
If the `rotate-root` endpoint changes the master password we're using to rotate all passwords, there can be a period of 1 or more seconds where the new password is propagating to all instances. During that time, if the `creds/:roleName` endpoint attempts to generate new credentials, it'll be hit and miss which password it should use - the old one, or the new one.
This PR adds code where if there's an error binding it tries the last master password if it was rotated within the last 10 minutes. This avoids attempting to catalogue the ways a password rotation error may present across different Active Directory implementations.
=> Try old password during rotation period

plugin/path_creds.go
The wrong error was being return causing failures to occur without any useful errors.
=> Return respErr

plugin/path_creds.go, plugin/path_creds_test.go, plugin/path_roles.go, plugin/util/passwords.go
In writing a test for https://github.com/hashicorp/vault/issues/6476, I found a couple of things, though I was unable to duplicate the fast-rolling behavior for that ticket:
- On first role read, the date for the password last having been updated in Active Directory was blank. This was because I was caching roles before having performed that check, so I fixed it by always invalidating the cache when a role is written to storage, and letting the caller cache the role if appropriate.
- Some debug output reported that the password was being rotated when actually, it was just being pulled, rotated if needed, and returned. That debug output is corrected.
- An error message was reporting that the minimum password length needed to be 8, when it actually needed to be 14. Fixes that.
- Adds a test …
=> Fixes from testing

plugin/backend_test.go, plugin/engineconf.go, plugin/path_config.go, plugin/path_creds.go
This solves the issue [here](https://github.com/hashicorp/vault/issues/6476) where a user was seeing Vault rotate passwords every time because their Active Directory cluster took _over_ a second to perpetuate the new password to all instances. Then Vault would see that the password was rotated _after_ it rotated it, and would re-rotate it to get back into sync. This situation was expected, but the time buffer for considering it in need of rotation was hard-coded as 1 second.
In reality, the amount of time it takes will correlate with the size of each Active Directory cluster, so this PR makes the time buffer configurable, now defaulting to 5 seconds to cover all environments we've seen so far.
=> Make time buffer configurable

plugin/path_config.go, plugin/path_config_test.go, plugin/path_creds.go, plugin/path_roles.go, plugin/path_rotate_root_creds.go
This PR converts `readConfig` to a static function so it'll be easier to reuse in areas where the entire back-end may not be available. In beginning work on this code, I know this will be needed so I'm breaking it into a very small and easy to read PR.
=> Make readConfig a static function

plugin/backend.go, plugin/backend_test.go, plugin/checkout_handlers.go, plugin/checkout_handlers_test.go
Wrapping the storage handler in #41 will be a password handler, introduced in this PR, whose sole responsibility is to roll passwords upon check-in.
On the first iteration of this code, I considered various approaches to mid-update failure. I could use a WAL, or I could use a deferred func that rolls back the password in the face of failure. However, upon reflection, I decided against this for the following reasons:
- If we spin off a WAL log that will be used to attempt updating the password every minute, the user could actually call back and rotate the password in the meantime, or the lending period could end and the overdue watcher could check it in. 
- If that happened, it would actually be desirable.
- It probably would make the most cognitive sense to a user or application that if …
=> Add password handler

go.mod, plugin/backend.go, plugin/backend_checkouts_test.go, plugin/checkout_handlers.go, plugin/checkout_handlers_test.go, plugin/path_reserves.go, vendor/modules.txt
This PR adds all endpoints related to managing a group of service accounts available for checkout, called a "reserve".
The endpoints added here are:
- `LIST /<mount>/library`
- `POST /<mount>/library/:name`
- `READ /<mount>/library/:name`
- `DELETE /<mount>/library/:name`
The next PRs I'm planning will be:
- One adding all endpoints related to check-ins and check-outs
- One adding an `OverdueWatcher` and finalizing the `CheckOutHandler` object model as per our team discussion
=> Add reserve API endpoints

plugin/backend.go, plugin/backend_checkouts_test.go, plugin/path_checkouts.go
Adds the following endpoint:
`READ /<mount>/library/:name/status`
```
{
"web-workers-1@example.com": {
"available": true
},
"web-workers-2@example.com": {
"available": false,
"borrower_entity_id": "some ID",
"lending_period": "4h",
"due": "2018-05-24T17:14:38.677370855Z"
}
}
```
=> Add checkout status endpoint

plugin/backend_checkouts_test.go, plugin/path_reserves.go
We'd discussed adding the ability to turn off enforcing that check-ins must be performed by the entity that performs the check-out, but we hadn't decided what it should be called.
This PR adds such a toggle called `"disable_check_in_enforcement"`. I'm open to other names if they seem better, but this was what sounded nice off the cuff.
=> Add enforcement toggle

plugin/backend_checkouts_test.go, plugin/checkout_handlers.go, plugin/checkout_handlers_test.go, plugin/path_checkouts.go, plugin/path_reserves.go
This PR replaces `lending_period` with `ttl` and `max_ttl`. This will allow us to leverage the existing leasing system for expiring and renewing check-outs.
=> Replace lending period with ttl and max ttl

.circleci/config.yml, Makefile, plugin/backend.go, plugin/backend_checkouts_test.go, plugin/checkout_handlers.go, plugin/checkout_handlers_test.go, plugin/path_checkout_sets.go, plugin/path_checkouts.go, plugin/path_checkouts_test.go
These endpoints are all PR'd together because they play into each other. How check-outs are done effects how check-ins, renewals, and revocations are done, and vice-versa. _Originally, race detection was not included in this PR due to size, but it was requested as part of the review so has been added._
This code has been tested at the CLI against a real AD server. All sunny paths work, including using the leasing system for checkout renewals and revocations (both manual revocations and ones due to a check-out expiring). TTL and maxTTL behavior has been tested and behaves as expected. 
This feature basically _looks_ complete from the outside now, though there's still more to do to make it prod-ready.
Still TODO (separately):
- Flatten the `CheckOutHandler` object model (#54, which will …
=> Add check-out, check-in, renewal, revocation, and race protection

go.mod, go.sum, plugin/path_checkouts.go, vendor/github.com/armon/go-metrics/.gitignore, vendor/github.com/armon/go-metrics/LICENSE, vendor/github.com/armon/go-metrics/README.md, vendor/github.com/armon/go-metrics/const_unix.go, vendor/github.com/armon/go-metrics/const_windows.go, vendor/github.com/armon/go-metrics/inmem.go, vendor/github.com/armon/go-metrics/inmem_endpoint.go, vendor/github.com/armon/go-metrics/inmem_signal.go, vendor/github.com/armon/go-metrics/metrics.go, vendor/github.com/armon/go-metrics/sink.go, vendor/github.com/armon/go-metrics/start.go, vendor/github.com/armon/go-metrics/statsd.go, vendor/github.com/armon/go-metrics/statsite.go, vendor/modules.txt
In our feature description, we also had the following:
>When a “400 Bad Request” is returned, we will log a debug-level statement regarding which credential was requested, and increment a metric about unavailable responses, to help us and others in detecting high resource contention that may contribute to customer issues.
This is added here.
=> Logging and metrics

plugin/path_checkout_sets.go, plugin/path_checkouts.go
When checkouts were unavailable, Vault was returning:
```
$ vault write -f ad/library/accounting-team/check-out
Error writing data to ad/library/accounting-team/check-out: Error making API request.
URL: PUT http://localhost:8200/v1/ad/library/accounting-team/check-out
Code: 400. Errors:
```
This improves that to be more explicit:
```
$ vault write -f ad/library/accounting-team/check-out
Error writing data to ad/library/accounting-team/check-out: Error making API request.
URL: PUT http://localhost:8200/v1/ad/library/accounting-team/check-out
Code: 400. Errors:
* No service accounts available for check-out.
```
Also includes a couple of CLI wordsmiths.
=> Improve unavailable response and CLI help

plugin/client/client.go, plugin/client/client_test.go, plugin/client/tools/simplecall.go, plugin/util/secrets_client.go
This PR addresses an issue where a user's `binddn` (which is used as the "root" account) was located in a separate tree from their `userdn`. More specifically, their `binddn` was from the Security organizational unit, and their `userdn` was from a separate, non-overlapping organizational unit. Since the code previously looked for the root account under the `userdn`, it wasn't finding the root account and couldn't rotate its credentials.
One solution would be for the user to set a `userdn` that encompassed them both, but it would have made searches take too long for their company.
This PR really only changes one thing - when `"ad/rotate-root"` is called to rotate root credentials, the _binddn_ is now used to search for it, allowing it to live happily in a separate tree. This will _always_ …
=> Allow binddn in separate tree

plugin/path_rotate_root_creds.go
Requests to `rotate-role` need to be forwarded from Performance Standby nodes to the Active node. This should happen on a read-only type error anyway, but these fields make it explicit. I've also refactored the `framework.Path` to use `Operations` and not the deprecated `Callbacks`
=> Forward rotation requests from standbys

plugin/path_rotate_root_creds.go
Backport #66 to `release/vault-1.4.x` branch
=> Backport: Forward rotation requests from standbys (#66)

plugin/backend_test.go, plugin/path_rotate_root_creds.go, plugin/path_rotate_root_creds_test.go
This looks to add support for a `vault write` or `POST` operation to rotate root credentials. This brings the overall user experience in line with the rest of the secrets plugins vault provides.
This change will not impact the existing `vault read` and `GET` operations, leaving existing workflows intact.
Support for routing to an `UpdateOperation` was added to the existing `ReadOperation`
[x] Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
[My Docs PR Link](https://github.com/hashicorp/vault/pull/9990)
[x] Add output for any tests not ran in CI to the PR description (eg, acceptance tests)
[x] Backwards compatible
```
/usr/local/go/bin/go test -json ./...
=== RUN   TestSearch
--- PASS: TestSearch (0.00s)
=== RUN   TestUpdateEntry
--- …
```
=> Add support for POST/write to rotate root credentials

plugin/config.go, plugin/config_test.go, plugin/passwords.go, plugin/passwords_test.go, plugin/path_config.go
This PR addresses an inconsistency in `ad/config` where password policies are set using the key `password_policy` but are returned using a different key when `ad/config` is read:
``` bash
$ vault write ad/config \
binddn=$USERNAME \
bindpass=$PASSWORD \
url=ldaps://138.91.247.105 \
userdn='dc=example,dc=com' \
password_policy='foobar' \
formatter='' \
length=0
$ vault read ad/config   
Key                             Value
---                             -----
binddn                          jasonodonnell
certificate                     n/a
formatter                       n/a
insecure_tls                    false
last_rotation_tolerance         5
length                          0
max_ttl                         768h
policy_name                     foobar
starttls …
```
=> Ensure read config returns correct password policy key

plugin/config.go, plugin/config_test.go, plugin/passwords.go, plugin/passwords_test.go, plugin/path_config.go
Since this was released in 1.5.x, backporting to that release (#71 ).
=> Backport: Ensure read config returns correct password policy key (#71)

README.md
Small change to the README to fix a redundant instruction.
=> Fix redundant instruction in README

plugin/path_creds.go
AD secret engine does lazy password rotation when `creds` are accessed. To reduce multiple password rotations, these requests should be forwarded to the active Vault node.
=> Update Router To Forward Creds Requests

plugin/path_creds.go
Backport of #76 because the backport automation failed.
=> Backport: Update router to forward creds requests (#76)

go.mod, plugin/backend.go, plugin/backend_test.go, plugin/path_creds.go, plugin/path_rotate_creds.go, plugin/path_rotate_root.go, plugin/path_rotate_root_test.go, plugin/rollback.go, scripts/docker/cleanup.sh, scripts/docker/setup.sh, scripts/docker/user.ldif
This adds a new endpoint, `rotate-role`, to allow for manual rotation of a service account in AD. Currently roles are only rotated when the `creds` are read from Vault.
If you would like to test this feature, I suggest using the Samba setup script included in this PR.
First, start the AD container:
```bash
cd ./scripts/docker
./setup.sh
```
Next, assuming Vault is checked out and is your current directory, compile Vault with this PR:
```bash
go get github.com/hashicorp/vault-plugin-secrets-ad@<COMMIT HASH HERE>
make dev
```
Next, start Vault and configure it to use the secret engine:
```bash
./bin/vault server -dev -dev-root-token-id=root &
export VAULT_TOKEN=root
export VAULT_ADDR=http://127.0.0.1:8200
vault login root
vault secrets enable ad
vault write ad/config \ …
```
=> Add rotate-role endpoint

CHANGELOG.md, go.mod, plugin/path_config.go, plugin/path_config_test.go
This PR fixes an issue in the `config` endpoint where the default `length` value is always set regardless of whether `password_policy` is provided. This leads to configuration errors unless `length=0` is explicitly provided. `password_policy` and `length` [are mutually exclusive](https://www.vaultproject.io/api-docs/secret/ad#password_policy), with preferred on `password_policy`, so the engine should understand that the value is ignored and not necessary if `password_policy` is provided.
```
vault write ad/config \
binddn=vagrant \
bindpass=vagrant \
url=ldaps://127.0.0.1 \
userdn='dc=Marti,dc=com' \
password_policy=example
Error writing data to ad/config: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/ad/config
Code: 500. Errors:
* 1 error occurred:
* cannot set …
```
=> config: set default length only if password policy is missing

plugin/backend_test.go, plugin/checkout_handler.go, plugin/client/fieldregistry.go, plugin/client/time.go, plugin/path_config.go, plugin/path_config_test.go
If a user tries to update the config and doesn't provide the binddn or bindpass, it will fail with an error: `cannot derive UserBindDN`. This PR adds a read operation to update to first check storage for a config and pass it into the config builder. I've added a test to cover this, which fails without the patch:
```bash
$ go test -v -run TestBackend
=== RUN   TestBackend
=== RUN   TestBackend/write_config
=== RUN   TestBackend/read_config
=== RUN   TestBackend/delete_config
=== RUN   TestBackend/update_config
backend_test.go:119: cannot derive UserBindDN
=== RUN   TestBackend/plant_config
=== RUN   TestBackend/write_role
=== RUN   TestBackend/read_role
=== RUN   TestBackend/list_roles
=== RUN   TestBackend/delete_role
=== RUN   TestBackend/plant_role
=== RUN   TestBackend/read_cred
=== …
```
=> Fix bug where updates to config would fail is password isn't provided

CHANGELOG.md
Updates the changelog for the upcoming plugin release
=> Update changelog in preparation for `v0.16.0` release

go.mod, go.sum, plugin/path_checkouts.go
[The recent dependencies upgrade workflow](https://github.com/hashicorp/vault-plugin-secrets-ad/actions/runs/6103301373/job/16563476510) failed due to 
```
go: downloading github.com/armon/go-metrics v0.5.1
go: github.com/armon/go-metrics@v0.5.1: parsing go.mod:
module declares its path as: github.com/hashicorp/go-metrics
but was required as: github.com/armon/go-metrics
...	        
Error: Process completed with exit code 123.	        
```
This PR will update github.com/armon/go-metrics v0.4.1 to github.com/hashicorp/go-metrics v0.5.1
=> update github.com/armon/go-metrics to github.com/hashicorp/go-metrics

go.mod, go.sum
downgrade hcl version for 0.20.1 release. Current hcl version in repository causes breaking changes within Vault
=> downgrade hcl version for 0.20.1
